server:
  port: 8766

spring:
  application:
    name: SERVICE-PROVIDER

  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/smbms?serverTimezone=UTC
    username: root
    password: ok

  jackson:
    date-format: yyyy-MM-dd

eureka:
  client:
    service-url:
      defaultZone:  http://localhost:8761/eureka/


mybatis:
  mapper-locations: classpath:mapping/*.xml
  type-aliases-package: com.zb.sp.entity
  configuration:
    auto-mapping-behavior: full


logging:
  level:
    com:
      zb:
        sp:
          dao:  debug
